### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by vanous** [jaketrent/svelte-getting-started#3]
Hello @jaketrent 

i know this is not the right place so feel free to close and erase, but i really wanted to thank you for your Plularsight Svelte getting started course, for me, this was an amazing experience.

Stay safe and healthy these days
cheers
Petr

**Comment by jaketrent** [comment]
@vanous , thank you for your note!  I'm touched by you taking the time to share this sincere thought with me.  I'm very glad that you had a great experience with the course.  That's more than I could have hoped for.  Good luck in your continued learning!

Many thanks,
Jake
